services:
  - type: web
    name: supply-api
    env: docker
    plan: free
    region: oregon
    repo: https://github.com/jan2022305846/SIMS.git
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_TIMEZONE
        value: UTC
      - key: APP_URL
        value: https://sims-laravel.onrender.com
      - key: APP_LOCALE
        value: en
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: APP_FAKER_LOCALE
        value: en_US
      - key: APP_MAINTENANCE_DRIVER
        value: file
      - key: PHP_CLI_SERVER_WORKERS
        value: 4
      - key: BCRYPT_ROUNDS
        value: 12
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_STACK
        value: single
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: mysql
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 240
      - key: SESSION_ENCRYPT
        value: false
      - key: SESSION_PATH
        value: /
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_HTTP_ONLY
        value: true
      - key: SESSION_SAME_SITE
        value: lax
      - key: FORCE_HTTPS
        value: true
      - key: SECURE_COOKIES
        value: true
      - key: ASSET_URL
        value: https://sims-laravel.onrender.com
      - key: MIX_ASSET_URL
        value: https://sims-laravel.onrender.com
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: file
      - key: CACHE_PREFIX
        value: ""
      - key: REDIS_CLIENT
        value: phpredis
      - key: REDIS_PASSWORD
        value: null
      - key: REDIS_PORT
        value: 6379
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_NAME
        value: SupplyAPI
      - key: AWS_DEFAULT_REGION
        value: us-east-1
      - key: AWS_USE_PATH_STYLE_ENDPOINT
        value: false
      - key: VITE_APP_NAME
        value: SupplyAPI

# Note: Sensitive environment variables should be set manually in Render dashboard:
# - APP_KEY=base64:o62Vb9Et2IDHxLrXlLK32brXyYsv2dpCv1Xhn/Adrhk= (your current production key)
# - DB_HOST=sql12.freesqldatabase.com (your current production host)
# - DB_PORT=3306 (your current production port)
# - DB_DATABASE=sql12798069 (your current production database)
# - DB_USERNAME=sql12798069 (your current production username)  
# - DB_PASSWORD=HekRxArZvq (your current production password)
# - RUN_MIGRATIONS=true (your current production setting)
# - SESSION_DOMAIN=sims-laravel.onrender.com (IMPORTANT: Set this to fix 419 CSRF errors)
# - MEMCACHED_HOST (if using memcached)
# - REDIS_HOST (if using redis)
# - MAIL_USERNAME (your email credentials)
# - MAIL_PASSWORD (your email password)
# - MAIL_FROM_ADDRESS (your from email)
# - AWS_ACCESS_KEY_ID (if using AWS)
# - AWS_SECRET_ACCESS_KEY (if using AWS)
# - AWS_BUCKET (if using AWS S3)
