<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>QR Code Scan Logs Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 20px; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; }
        .date-range { text-align: center; margin-bottom: 20px; font-style: italic; }
        .log-entry { margin-bottom: 20px; border: 1px solid #ddd; padding: 15px; }
        .timestamp { font-weight: bold; font-size: 14px; color: #007bff; margin-bottom: 5px; }
        .activity { font-size: 13px; color: #333; }
        .no-logs { text-align: center; padding: 40px; color: #666; font-style: italic; }
    </style>
</head>
<body>
    <div class="header">
        <h1>QR Code Scan Logs Report</h1>
        <div class="date-range">
            Period: {{ $data['period'] }} - {{ $data['current_date'] }}
        </div>
        <p>Generated on: {{ date('M d, Y H:i') }}</p>
    </div>

    @if($data['records']->count() > 0)
        @foreach($data['records'] as $log)
            <div class="log-entry">
                <div class="timestamp">
                    {{ $log->created_at->format('M d, Y H:i:s') }}
                </div>
                <div class="activity">
                    @php
                        $userName = $log->user->name ?? 'System';
                        $itemName = $log->item->name ?? 'Unknown Item';

                        // Determine if this was an update or just a scan
                        $isUpdate = str_contains(strtolower($log->action ?? ''), 'update') ||
                                   str_contains(strtolower($log->action ?? ''), 'location') ||
                                   str_contains(strtolower($log->action ?? ''), 'edit');

                        if ($isUpdate) {
                            echo $userName . ' updated item (' . $itemName . ') location';
                        } else {
                            echo $userName . ' scanned item (' . $itemName . ')';
                        }
                    @endphp>
                </div>
            </div>
        @endforeach
    @else
        <div class="no-logs">
            No QR scan activity found for the selected period.
        </div>
    @endif

    <div class="footer">
        <p>This report was generated by the Supply Office Management System</p>
        <p>Confidential - For internal use only</p>
    </div>
</body>
</html>