<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>QR Scan Logs Report - {{ ucfirst($data['period']) }} {{ $data['selection'] }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #007bff;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #007bff;
            margin: 0;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .summary {
            display: table;
            width: 100%;
            margin-bottom: 30px;
            border-collapse: collapse;
        }
        .summary-card {
            display: table-cell;
            width: 25%;
            padding: 15px;
            text-align: center;
            border: 1px solid #ddd;
            background: #f8f9fa;
        }
        .summary-card h3 {
            margin: 0;
            font-size: 28px;
            color: #007bff;
        }
        .summary-card p {
            margin: 5px 0 0 0;
            font-size: 12px;
            color: #666;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        .table th, .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-size: 11px;
        }
        .table th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .table tbody tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 1px solid #dee2e6;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
        .period-info {
            background: #e9ecef;
            padding: 15px;
            margin: 20px 0;
            border-radius: 5px;
        }
        .page-break {
            page-break-before: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>QR Scan Logs Report</h1>
        <p><strong>Period:</strong> {{ ucfirst($data['period']) }} - {{ $data['selection'] }}</p>
        <p><strong>Report Date:</strong> {{ date('F d, Y') }}</p>
        <p><strong>Date Range:</strong> {{ $data['dateFrom'] }} to {{ $data['dateTo'] }}</p>
    </div>

    <div class="summary">
        <div class="summary-card">
            <h3>{{ number_format($data['summary']['totalScans']) }}</h3>
            <p>Total Scans</p>
        </div>
        <div class="summary-card">
            <h3>{{ number_format($data['summary']['uniqueItems']) }}</h3>
            <p>Unique Items Scanned</p>
        </div>
        <div class="summary-card">
            <h3>{{ number_format($data['summary']['activeUsers']) }}</h3>
            <p>Active Scanners</p>
        </div>
        <div class="summary-card">
            <h3>{{ number_format($data['summary']['todayScans'] ?? 0) }}</h3>
            <p>Today's Scans</p>
        </div>
    </div>

    <div class="period-info">
        <strong>Scan Summary:</strong> This report shows all QR code scanning activities during the selected period.
        Each scan represents an inventory verification or item access event.
    </div>

    <h2>QR Scan Activity Logs</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Timestamp</th>
                <th>Item Scanned</th>
                <th>User</th>
                <th>Scanner Type</th>
                <th>Location</th>
                <th>IP Address</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['scans'] as $scan)
            <tr>
                <td>{{ $scan->created_at->format('M d, Y H:i:s') }}</td>
                <td>{{ $scan->item ? $scan->item->name : 'Unknown Item' }}</td>
                <td>{{ $scan->user ? $scan->user->name : 'Unknown User' }}</td>
                <td>webcam</td>
                <td>{{ $scan->office ? $scan->office->name : 'N/A' }}</td>
                <td>N/A</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    @if($data['scans']->isEmpty())
    <div style="text-align: center; padding: 50px; background: #f8f9fa; border: 1px solid #dee2e6; margin: 20px 0;">
        <h3 style="color: #6c757d; margin: 0;">No QR Scan Data Found</h3>
        <p style="color: #6c757d; margin: 10px 0 0 0;">No scanning activity was recorded during the selected period.</p>
    </div>
    @endif

    <div class="footer">
        <p>Generated by Supply Office Management System on {{ date('F d, Y \a\t H:i:s') }}</p>
        <p>This report contains scanning activity logs for audit and inventory tracking purposes.</p>
    </div>
</body>
</html>